---
title: "HarvardX Data Science Capstone"
author: "Codrin Kruijne"
date: "22/05/2019"
output:
  pdf_document: default
---

This report has been prepared for the [HarvardX Data Science program] ](https://www.edx.org/professional-certificate/harvardx-data-science) Capstone course final project submission and consists of three files of original work that can be found on GitHub (with all commits): this [report in PDF](), this [report in R markdown] and an [R markdown script file]() with all the code (also [knitted to PDF with results]() for convenience). Next to the course requirements my learning goal was to get familir with parallel processing and explore using [AutoML](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html) with [H2O in R](https://cran.r-project.org/package=h2o).


# Introduction

The dataset consists of 10M movie ratings by users, including movie title, year and genre. The goal of the assignment was to devise a way to predict movie ratings. I generated predictions derived from user and movie characteristics, using linear regression and applying AutoML. Model performances was assessed using RMSE. Derived models, requiring little computation, get up to an average of X deviation from the actual ratings, the best linear model achieve Y and the ensemble models from autoML reach an impressive Z.

# Analysis

## Recommendation systems
Exploring infromation on recommender systems from the course[^1] and on Wikipedia[^2], algorithms can roughly be based on collaborative filtering (recommendations based on users with similar behaviour) or content-based filtering (recommendation based on )

## Raw data
Training and validation datasets were provided, with about 10M and 1M records respectively, which may be a challenge to compute complex models on a laptop. The data is a combination of user (identity), movie (title, year and genre) and rating (rating on a scale of 1 to 5 and date) characteristics.

## Data preparation
To derive some mor

## Data exploration
visualization, any insights gained

## Modeling
approach and results


# Conclusion


# References
[^1]: [Winning the Netflix Prize: A Summary](http://blog.echen.me/2011/10/24/winning-the-netflix-prize-a-summary/)
[^2]: [Wikipedia article "Recommender system"](https://en.wikipedia.org/wiki/Recommender_system)